# Configuracion de Base de Datos leyendo directamente de las variables de entorno
spring.datasource.url=${spring.datasource.url}
spring.datasource.username=${spring.datasource.username}
spring.datasource.password=${spring.datasource.password}

# Configuracion de Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL}

# Configuracion de Registro en la Nube
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME}

# Asegura el nombre de la aplicacion para que el Gateway pueda encontrarla
spring.application.name=service-usuarios