# Puerto y Nombre
server.port=8081
spring.application.name=service-productos

# Configuracion Eureka (Comun)
# Solo apuntamos a la variable, si no se carga, el servicio debe fallar al inicio
eureka.client.service-url.default-zone=${EUREKA_URL}

# Configuracion necesaria
spring.main.allow-bean-definition-overriding=true