# Mapeo de variables de entorno hacia las propiedades de Spring
spring.datasource.url=${spring.datasource.url}
spring.datasource.username=${spring.datasource.username}
spring.datasource.password=${spring.datasource.password}

# Eureka y Registro
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME}

# Asegura el nombre de la app (cambia según corresponda a cada servicio)
# Para Productos:
spring.application.name=service-productos