# Puerto y Nombre
server.port=8081
spring.application.name=service-productos

# Configuracion Eureka (Común)
eureka.client.service-url.default-zone=${EUREKA_URL:http://localhost:8761/eureka/}

# Configuracion necesaria
spring.main.allow-bean-definition-overriding=true