# Puerto
server.port=8082

# Identificador del servicio
spring.application.name=service-pedidos

# Configuracion Eureka
# Usamos directamente la variable de entorno
eureka.client.service-url.default-zone=${EUREKA_URL}