# Puerto
server.port=8082

# Identificador del servicio
spring.application.name=service-pedidos

# Configuración Eureka (Común para todos los perfiles)
eureka.client.service-url.default-zone=${EUREKA_URL:http://localhost:8761/eureka/}

# Nota: La configuración de base de datos se maneja
# en application-local.properties y application-railway.properties