# Ajuste para Render
# Usamos el nombre del host que Render nos asigna
eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME:localhost}
eureka.client.service-url.default-zone=http://${eureka.instance.hostname}/eureka/

# Forzamos el puerto, en Render suele ser el 80 o el 10000 segun la configuracion del contenedor
server.port=${PORT:8080}