server.port=8761

# Estas 2 líneas evitan que el servidor intente buscar a otros pares
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

spring.application.name=service-eureka