# Cuando subas a Railway, esta variable sera la URL que te de Railway s
eureka.instance.hostname=${EUREKA_HOST}
eureka.client.service-url.default-zone=http://${eureka.instance.hostname}:${server.port}/eureka/