# Registro en Eureka
eureka.client.service-url.default-zone=${EUREKA_URL}

# Configuracion para que el Gateway sea "descubrible"
eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME:localhost}
server.port=${PORT:8080}