# ==========================================
# CONFIGURACION DEL SERVIDOR
# ==========================================
spring.application.name=service-gateway
server.port=8080

# ==========================================
# CONEXION A EUREKA
# ==========================================
# Usamos la variable EUREKA_URL para la nube, y localhost para local
eureka.client.service-url.defaultZone=${EUREKA_URL}

# ==========================================
# RUTAS DEL API GATEWAY
# ==========================================

# Ruta hacia Productos
spring.cloud.gateway.routes[0].id=route-productos
spring.cloud.gateway.routes[0].uri=lb://service-productos
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/productos/**, /api/categorias/**

# Ruta hacia Usuarios
spring.cloud.gateway.routes[1].id=route-usuarios
spring.cloud.gateway.routes[1].uri=lb://service-usuarios
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/usuarios/**

# Ruta hacia Pedidos
spring.cloud.gateway.routes[2].id=route-pedidos
spring.cloud.gateway.routes[2].uri=lb://service-pedidos
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/pedidos/**
