# Registro en Eureka
eureka.client.service-url.default-zone=http://eureka-server-e6up.onrender.com/eureka/

# Configuracion para que el Gateway sea "descubrible"
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME}