# Configuraciones de produccion
logging.level.root=INFO

# Registro en Eureka (usando la variable que configuramos en Render)
eureka.client.service-url.default-zone=${EUREKA_URL}

# Nombre del servicio (para que Eureka lo identifique bien)
spring.application.name=service-frontend

# Configuracion de red para Render
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME:localhost}
server.port=${PORT:8080}