spring.application.name=service-frontend
server.port=8085

# Configuración de Thymeleaf
spring.thymeleaf.cache=false

# Eureka (Configuración híbrida lista para local y nube)
eureka.client.service-url.default-zone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true