# Configuraciones de produccion
logging.level.root=INFO

# Registro en Eureka Usando la variable de entorno es mas seguro
eureka.client.service-url.defaultZone=${EUREKA_URL}

# HABILITAR EUREKA
eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Nombre del servicio
spring.application.name=service-frontend

# Configuracion de red para Render
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME}
server.port=${PORT:8080}