spring.application.name=service-frontend
server.port=8085

# Configuracion de Thymeleaf
spring.thymeleaf.cache=false

# Eureka (Configuracion base)
eureka.client.service-url.default-zone=${EUREKA_URL}
eureka.instance.prefer-ip-address=true